name: Code & Infrastructure Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Terraform Format & Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Init & Validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate

  helm-lint:
    name: Helm Chart Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.14.0'

      - name: Run Helm Lint
        run: helm lint helm/microservices-chart/

  yaml-lint:
    name: YAML Syntax Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: manifests/
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable